### PR TITLE
Added promisified actions

### PR DESCRIPTION
**Pull request by tobilg**
This PR contains the promisified versions of the Dataframe actions you outlined in #28. I chose to reuse the ...Async methods and not having node-java generate the promisified versions for *all* methods.

### CODE REVIEW

**Comment by tobilg** [comment]
If you decide to eventually merge this, it would be great if you could also publish a new module version to NPM. Thanks.

**Comment by henridf** [comment]
thanks! looks great from a very quick look; i'll take a closer look before merging (which may not be before the weekend)

**Comment by tobilg** [comment]
Originally it was an own PR, but unfortunately I committed it to Master before creating the branch for the promisified actions. Still not a Git pro, I guess... Sorry. Will fix the Dockerfile as well.

**Comment by henridf** [comment]
Ok, this all looks good, just a couple small things before merging 
- I'd prefer promised functions to simply end in `P` rather than `Promised` (e.g. `jsonP`)
- test comments above

thanks!

**Comment by tobilg** [comment]
I'll not be able to work on this this week unfortunately...

**Comment by henridf** [comment]
@tobilg just to be sure i take it you no longer plan to work on this? tx

**Comment by tobilg** [comment]
Sorry, I'll not be able to implement the changes you want due to time constraints.

**Pull request closed without merging**
